---
site_name: lsu-hackfest
# where do you want messages to go ?
slack_channel: lagos-hackfest
java6_name:
  Debian: java-1.6.0-openjdk
  RedHat: java-1.6.0-openjdk
java7_name:
  Debian: java-1.7.0-openjdk
  RedHat: java-1.7.0-openjdk
managed_prerequisites:
 - python2.7
 - python-simplejson
prerequisites:
  Debian:
    - vim
    - make
    - git
    - python-pip
    - python-setuptools
    - python-dev
    - libssl-dev
    - gcc
    - nano
    - joe
    - libffi-dev
    - php5-curl
    - php5-cli
    - jq
  RedHat:
    - vim
    - make
    - git
    - python-pip
    - python-setuptools
    - python-devel
    - gcc
    - libffi-dev
    - php5-curl
    - php5-cli
    - jq
glibrary:
  admin_user: hackfest
  admin_email: hackfest@ct.infn.it
  url: https://glibrary.ct.infn.it:3500
